### ISSUE TITLE
Trial signed plugins

### ISSUE THREAD

**Issue by pecko** [debrief/debrief#184] opened 2014-05-19 20:12 UTC
_[Migrated from Assembla ticket [184](https://www.assembla.com/spaces/Debrief/tickets/184) - reported by @IanMayo on 2009-12-03 10:21:32]_

Users currently receive a warning indicating that they're about to load an unsigned plugin.

Trial signing plugins & features, and get a permanent key if necessary

There would be merit in investigating how to sign plugins, plus the process involved in obtaining a suitable certificate/key.

**Comment by IanMayo** [comment] 2018-02-08 10:00
Closing, duplicate of #677

**Closed by IanMayo** 2018-02-08 10:01 UTC
