### ISSUE TITLE
While maximizing D-Lite, the map area doesn't expand

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3695] opened 2019-02-05 09:28 UTC
Screenshot:
[![Image from Gyazo](https://i.gyazo.com/f914ea0498a5acdbe86924541b4468c1.png)](https://gyazo.com/f914ea0498a5acdbe86924541b4468c1)

The map area should be expanded when D-Lite gets maximized.
When D-Lite launches it looks like this:
[![Image from Gyazo](https://i.gyazo.com/07ef81019c203c44800b83bdf69dda20.png)](https://gyazo.com/07ef81019c203c44800b83bdf69dda20)
But when we maximize it , it looks like the first picture. So as can be seen from the 2 pictures, the map area doesn't acquire new size when we maximize D-Lite.

**Comment by IanMayo** [comment] 2019-03-13 13:32
This is a duplicate of other issue - associated to resizing the window.

**Closed by IanMayo** 2019-03-13 13:32 UTC
Labels: D-Lite, bug

**Comment by helenayele** [comment] 2019-03-14 10:37
yes it is tracked at #3719
