### ISSUE TITLE
Code completion issue on Script Shell

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3496] opened 2018-11-26 15:58 UTC
Video
[![Image from Gyazo](https://i.gyazo.com/5d478d1e4cbf228763b20ef3c0300403.gif)](https://gyazo.com/5d478d1e4cbf228763b20ef3c0300403)

It remembers what is typed before.

But before writing any statement, trying to invoke content assist on getActi{here}
 works as expected.

**Comment by IanMayo** [comment] 2018-11-26 16:10
oh yeah, it looks like there are two code completions: one for the JS object, the other for entries in the history.  It's using the one from the history (which includes the var defn).

**Comment by IanMayo** [comment] 2018-11-26 16:11
oh yeah, it looks like there are two code completions: one for the JS object, the other for entries in the history.  It's using the one from the history (which includes the var defn).

Aah, it won't have auto-complete for that object, not yet.  That's a future step.

you'll have to type it in by hand, for now.

**Comment by IanMayo** [comment] 2018-11-26 16:18
Closing this - it's expected behaviour.

**Closed by IanMayo** 2018-11-26 16:18 UTC
