### ISSUE TITLE
GeoPDF - Check Special characters in the track names while generating the Geojson

### ISSUE THREAD

**Issue by saulhidalgoaular** [debrief/debrief#4984] opened 2020-10-01 08:13 UTC
Analysts had trouble yesterday. couldn't find geojson file. it was for track titled F/V SOMETHING.
Debrief interpreted the / as a folder separator.  We need to make the track name "safe" for use in a file path

**Comment by helenayele** [comment] 2020-10-01 15:28
@saulhidalgoaular / @IanMayo , could you please provide steps to verify this issue ?

**Comment by saulhidalgoaular** [comment] 2020-10-01 15:31
Hello @helenayele 

I have provided a sample file in the PR. Export it to GeoPDF. If it is a correct PDF, then it was fixed.

You could try different filenames in the track also.

**Comment by IanMayo** [comment] 2020-10-01 15:33
Sure.  You just need to name a track `F/V SOMETHING`.   Debrief pushes the GeoPDF data to a temporary data-file that contains the track name.  But, when it tries to read it back in, it interprets the `/` as a folder separator, and can't find the file.

Saul's fix ensures the data-file is produced using a `safe` format of the filename.

So, in the current `develop` branch, loading `PlotWithGeoTiff.dpf`, then changing a track name to include `/` should fail in export to GeoPDF (file not found).

But, doing it in this branch should be fine.

**Comment by helenayele** [comment] 2020-10-01 20:22
Okay thanks so much for your brief explanations!
It works with the example file provided in the PR.
But after I open the rep file I renamed the track name like [![Image from Gyazo](https://i.gyazo.com/40be596c3c6eaf4bd71f97429368ce44.png)](https://gyazo.com/40be596c3c6eaf4bd71f97429368ce44)
And export to pdf I get an error
[![Image from Gyazo](https://i.gyazo.com/5e25913ebdb9e5e6437086eeab28b802.png)](https://gyazo.com/5e25913ebdb9e5e6437086eeab28b802)

**Comment by helenayele** [comment] 2020-10-01 20:23
due to the above comment , re-opening..

**Comment by IanMayo** [comment] 2020-10-02 12:00
@helenayele , this export just worked for me in `develop`:
![image](https://user-images.githubusercontent.com/1108513/94920806-ece23380-04ae-11eb-9fec-63fe25733951.png)

I think the issue may have been resolved, could you re-test please?

**Comment by helenayele** [comment] 2020-10-02 15:02
Okay now I can't reproduce the issue shown above.

[![Image from Gyazo](https://i.gyazo.com/35d2f1d9d9da4a934c84f23a7ea036f9.png)](https://gyazo.com/35d2f1d9d9da4a934c84f23a7ea036f9)

Closing...

**Closed by helenayele** 2020-10-02 15:02 UTC
