### ISSUE TITLE
blank progress dialog on import replay/dpf file

### ISSUE THREAD

**Issue by ayeshare** [debrief/debrief#4190] opened 2019-05-22 09:56 UTC
see the last comment on 
https://github.com/debrief/debrief/issues/3809#issuecomment-492619262

The issue is that the progress dialog is showing up as blank dialog with nothing displayed.  The progress monitor was displaying correctly before we introduced the ribbon for the toolbar.
The ribbon requires we launch the app, asynchronously, therefore SwingUtilities.invokeLater() is used.  

Steps to reproduce:
Open or drag/drop a large rep file such as `Bulk_red_tracks.rep` from sample_data.

The progress dialog popsup which shows a blank dialog.

I tried using SwingWorker to import the rep file, this works only in the case of narratives replay file as there are no ui calls. Running the import (reading file) process in background, showed the progress dialog correctly.

**Comment by ayeshare** [comment] 2019-05-22 10:02
Steps to reproduce:
Open or drag/drop a large rep file such as Bulk_red_tracks.rep from sample_data.
The progress dialog popsup which shows a blank dialog.

**Comment by ayeshare** [comment] 2019-05-22 10:07
I tried using SwingWorker to import the rep file, this works only in the case of narratives replay file as there are no ui calls.  Running the import (reading file) process in background, showed the progress dialog correctly.

**Comment by IanMayo** [comment] 2019-05-22 10:16
Note: it's in this method that we introduce alternate processing for narrative layers, and non-narrative layers:
https://github.com/debrief/debrief/pull/4182/files#diff-921d46aa6c1f0efb06e0bf4506b15099R909

**Comment by helenayele** [comment] 2019-05-23 11:37
@ayeshare  this issue is a duplicate of #3809

**Closed** 2019-05-31 12:25 UTC
Labels: D-Lite, bug

**Comment by helenayele** [comment] 2019-05-31 13:21
The progress dialog is not blank and no exception is also thrown so verifying...
[![Image from Gyazo](https://i.gyazo.com/90343092426ffc1d0139896beb5f0439.gif)](https://gyazo.com/90343092426ffc1d0139896beb5f0439)
