### ISSUE TITLE
Performance issue on large sensor file on full debrief

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4483] opened 2019-08-28 13:54 UTC
When I try to change the visibility of items in `Sample_lots_of_sensors.dpf` file,full debrief is very slow, it turns to not-responding state and comes back again to responding state. Please see the below video.

https://screencast-o-matic.com/watch/cqjuI5tYd1

### Steps :
1. Load `Sample_lots_of_sensors.dpf` file
2. On outline view, select each sensors to make them visible.
3. Again select items from Chart Features layer and make them visible
4 See that Full debrief is so slow while applying changes.

**Comment by IanMayo** [comment] 2019-08-28 16:35
Helen, I'm pretty sure this is a duplicate of #4480 , D-Lite is very slow in updating very large Outline Views

**Closed by IanMayo** 2019-08-28 16:35 UTC
Labels: bug
