### ISSUE TITLE
Difficulty in closing edit properties window

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4060] opened 2019-04-19 13:51 UTC
Edit property window is not closed even if I click close button 3-4 times.

Video:
[![Image from Gyazo](https://i.gyazo.com/ba07694daef54b10efcaa79157953c3c.gif)](https://gyazo.com/ba07694daef54b10efcaa79157953c3c)

### Expected Result:
It should be closed with a single click of Close button.

**Comment by saulhidalgoaular** [comment] 2019-04-19 16:29
Good afternoon @Helen Ayele. I am trying to reproduce it, but it works normally in my computer.
Maybe there is a missing step or maybe it is due a cpu power.

**Comment by helenayele** [comment] 2019-04-22 07:41
### Steps to reproduce :

1. Open sample.dpf file in D-Lite by dragging , Select Fit to window from view menu
2.  Open Time menu and try to change start and end date from Filter to time 
3. Play
4. While playing open edit-time properties window , try to change small steps or other property and click Apply , then try to close it by selecting close button

Note:
I think the slowness is created after selecting apply button, even if you didn't change anything, when you select apply . and click Close it will take time to close the property window

O

**Comment by IanMayo** [comment] 2019-04-26 08:41
@helenayele - I tried those exact steps, and it worked perfectly.  But, I'm under Macos.

Will have to try under MS Windows.

**Comment by IanMayo** [comment] 2019-04-26 10:14
I've also asked @ayeshare to see if it happens for her under MS Windows.

**Comment by saulhidalgoaular** [comment] 2019-04-26 19:35
Good afternoon. Yes, I have tried this on MS Windows too and for me it worked well.

**Comment by ayeshare** [comment] 2019-04-29 13:19
With the given steps I cant replicate it.

**Comment by helenayele** [comment] 2019-04-30 13:48
OS version please?

**Comment by IanMayo** [comment] 2019-04-30 13:52
Hmm, from watching the video, is the Apply button stuck in a recursive loop?  It stays blue after it has been clicked.

**Comment by helenayele** [comment] 2019-04-30 14:27
Yes ,definitely it stuck for some time.

**Comment by saulhidalgoaular** [comment] 2019-06-01 17:52
Good afternoon.

I think it is related with #4054 , I have tested it on the same computer, but I cannot reproduce it. I am using Windows 7 Professional Edition 32 bits.

Section of code that runs that button is just checking what properties have changed and it comes from Debrief Legacy. Does it happen to you in Debrief Legacy too?

**Comment by helenayele** [comment] 2019-06-03 06:44
>Does it happen to you in Debrief Legacy too?
No it is not reproducible in Debrief Legacy. It seems debrief legacy is too lightweight than D-Lite.
[![Image from Gyazo](https://i.gyazo.com/4ca39550968d7316418f7e92abfff4af.gif)](https://gyazo.com/4ca39550968d7316418f7e92abfff4af)

**Comment by IanMayo** [comment] 2019-06-03 12:23
Hmm, @saulhidalgoaular & @helenayele - the difference from Classic is that D-Lite is doing a refresh of the Outline View, and for some reason, these happen really slowly on Helen's laptop.

I've spoken to the scientists that are our customer representatives, and have indicated that i5 is the minimum processor necessary to run Debrief.

I'm going to close this issue.

**Closed by IanMayo** 2019-06-03 12:23 UTC
Labels: D-Lite, bug
