### ISSUE TITLE
Reduce size of build

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1281] opened 2015-06-23 17:21 UTC
Travis is regularly failing.

Peco & Ian think it's down to either the build time, or the build size.

Debrief would certainly benefit from trimming some fat.  Suggest trimming these areas:
* duplicate instances of jars
* old (unused) images
* unused jars

Any other areas where we can trim excess @pecko ?

**Comment by pecko** [comment] 2015-06-23 18:03
Removing some bigger file from history will help.

**Comment by pecko** [comment] 2015-06-23 18:04
Also we can skip creating source bundles.

**Comment by IanMayo** [comment] 2015-06-23 18:04
"bigger file from history" = you mean the git history?

I thought our problem was the size of the app being built.

**Comment by pecko** [comment] 2015-06-23 18:14
Yes, from git history
I think that size of complete build is important. Since travis clone git repository the history is included (I think the latest 50 commit or something similar).
When running tests tycho creates an Eclipse distribution (50MB). It probably would help if we could clean tests before creating dist files

**Comment by pecko** [comment] 2015-06-23 21:37
Seems the issue happens because we added the asset plugin to build (it increases their target dirs and the editable.test plugin).

I have created the PR https://github.com/debrief/debrief/pull/1283 with the following features:

- skip creating source plugins (we don't use them)
- remove building the media plugin (it isn't included in distribution)
- remove duplicated geotools libraries
- remove unused eclipselink.jar

The build succeed twice.
I have tried locally and the debrief repo (after build) was 3.2 GB; now is 2.9 GB 

I hope it will be fine now.

We could still to do the following:

- remove sources libraries from the geotools plugin; it will decrease plugin for cc 9MB (and for all 4 distribution)
- move the asset plugin/product to separate git repository (require creating base debrief p2 dependencies and host them anywhere)
- review openmap in the o.m.cmap.legacy plugin; this plugin requires different version of openmap than the openmap plugin
- try to clean tests as described here

**Comment by IanMayo** [comment] 2015-06-24 14:32
ok - hopefully our new changes have restored the reliable build.  Let's keep an eye on it for a few days, and see how it turns out.

**Comment by pecko** [comment] 2015-06-24 16:44
Builds seems more stable now. Several latest builds succeed.

**Comment by pecko** [comment] 2015-09-12 23:18
I close this issue. We have https://github.com/debrief/debrief/issues/1296 related to this issue.
Travis team increases build size significant, so we just should care about github limits. https://github.com/debrief/debrief/issues/1296 also contains a list of big files. This issue is a duplicate of that.

**Closed by pecko** 2015-09-12 23:18 UTC
Labels: build
