### ISSUE TITLE
Introduce SLD editor for shapefile layers

### ISSUE THREAD

**Issue by pecko** [debrief/debrief#396] opened 2014-05-19 20:15 UTC
*[Migrated from Assembla ticket [397](https://www.assembla.com/spaces/Debrief/tickets/397) - reported by @IanMayo on 2011-09-13 13:52:55]*

We can load shapefiles, but by default we are only showing lines and shading.

We do not allow color editing, nor the ability to show text labels.

Andrea's SWT work includes an SLD editor.  I suspect we should either include the SLD editor, or let the ShapeFile layer have properties that on editing are propagated to the underlying shapefile-layer.

There is lots and lots of third-party data avaialble in ShapeFile (including Natural Earth).  We'd need something like this to be able to tidily display that data.

**Comment by IanMayo** [comment] 2015-01-30 15:09
Duplicate of #1031

**Closed by IanMayo** 2015-01-30 15:09 UTC
Labels: ImportedAssembla
