### ISSUE TITLE
NPE logged while saving map without a track

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3874] opened 2019-03-19 11:14 UTC
After inserting shapes to D-Lite without opening track, when I try to save the map, it throws NPE with attached stack-trace
[NPE_while_saving_map.txt](https://github.com/debrief/debrief/files/2982960/NPE_while_saving_map.txt)

### Steps:

1. Launch D-Lite
2.Insert Line, lable and circle shapes
3. Select New > then Save
.

**Comment by IanMayo** [comment] 2019-03-19 17:06
Close. Duplicate of #3857

**Closed by IanMayo** 2019-03-19 17:06 UTC
Labels: D-Lite, bug

**Comment by helenayele** [comment] 2019-03-20 07:06
Yes, no more reproducible after fixing #3857
