### ISSUE TITLE
Expanding the XY Plot View, Plot disappears  (MS WINDOWS)

### ISSUE THREAD

**Issue by nimeshp27** [debrief/debrief#728] opened 2014-09-22 13:02 UTC
Steps:
1. Load sample.xml file
2. Select two tracks together
3. RIght click on select "XY" plot
4. Select the attribute as Range and select any Primary track and click on "OK" button
5. XY Plot should appear at the bottom
6. Now expand the Plot section

Issue: Plot doesn't appear

See the video here:
https://www.dropbox.com/s/7x22wtbym14cido/XY%20Plot%20doesn%27t%20appear.avi?dl=0

**Comment by IanMayo** [comment] 2015-02-02 12:46
I just saw this again today.

It happened when the XY Plot was being resized. Duh, I forgot to look at the log file.

But, I do suspect that it's related to JFreeChart continuously redrawing the chart as the resize happens.  I wonder if it's a threading issue?

Alternatively, we should probably disable redrawing until the user has finished resizing the plot.

Let's come back to this if/when I've found a log file.

**Comment by pecko** [comment] 2015-02-04 07:53
@IanMayo You have reproduced the issue on Linux. Right?

**Comment by IanMayo** [comment] 2015-02-04 08:35
No, sadly not.

**Comment by IanMayo** [comment] 2015-02-06 09:31
I was doing a demo with Windows in a VM under OSX.  The XYPlot froze each time I tried to adjust the RCP View size.  Well, it didn't free, it was just white for about 5 seconds before it appeared.  On other occasions, after resizing the view it stayed white, only appearing when I tried to resize the view a tiny amount.

We should get this fixed.  Maybe a good first step is to switch off "live redraw", and only redraw the JFReeChart once the resize operation has completed.

**Comment by pecko** [comment] 2015-02-07 01:22
What plot you are using? sample.dpf? 
Will try to reproduce. It probably requires some bigger load.

> We should get this fixed. Maybe a good first step is to switch off "live redraw", and only redraw the 
> JFReeChart once the resize operation has completed.

You can try the **Auto-sync with calculated track data** action off. I could try, but I can't reproduce the issue.

**Comment by IanMayo** [comment] 2015-02-07 10:01
To be honest, it seemed to happen in all plots.  When I'm at my desk I'll put together a reproducible example.

**Comment by pecko** [comment] 2015-02-07 17:19
> We should get this fixed. Maybe a good first step is to switch off "live redraw", and only redraw the 
> JFReeChart once the resize operation has completed.

The Eclipse presentation framework refresh views/editor while resizing. I don't sure if we can change something here.

I have tried to play with SWT_AWT components according to http://git.eclipse.org/c/platform/eclipse.platform.swt.git/tree/examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet154.java
See the PR https://github.com/debrief/debrief/pull/1091
It isn't ready to merge; have to play more...
There is the SWT.NO_REDRAW_RESIZE flag, but it's only hint and not sure it helps.

I can see a little difference when playing with these options (delay is smaller or bigger, but it is always less than 1 second). I suppose that the issue happens on slower machine (or embeded VM).

**Comment by IanMayo** [comment] 2015-02-25 09:36
Finished

**Comment by IanMayo** [comment] 2015-02-25 13:56
Still failing. When the first xy-plot is opened, it pauses for 30 seconds or so - after which it is displayed.

After this pause it drags/resizes perfectly.

On closing and re-opening Debrief the problem returns - but just for the first plot resize.

**Comment by IanMayo** [comment] 2015-03-30 15:36
I'm going to see if this goes away under Luna builds.  I know charts are broken in OSX, but were fixed for Luna.  #hopefully

**Comment by IanMayo** [comment] 2015-05-06 07:23
Fixed with move to SWT charts #1169

**Closed by IanMayo** 2015-05-06 07:23 UTC
