### ISSUE TITLE
PPT marker sometimes doesn't move according to the footprints.

### ISSUE THREAD

**Issue by saulhidalgoaular** [debrief/debrief#3381] opened 2018-11-06 07:26 UTC
Steps to reproduce:
1. Open sample.dpf.
2. Export a portion of the movement to pptx.

Sometimes the Power point file generated doesn't show movement using Microsoft Power Point 365.

**Comment by saulhidalgoaular** [comment] 2018-11-06 07:34
[DebriefExport-95_12_12_10_36.PPTX](https://github.com/debrief/debrief/files/2552040/DebriefExport-95_12_12_10_36.PPTX)
This is an example of the file generated.

**Comment by IanMayo** [comment] 2018-11-06 07:39
Ok.  So, the tracks appear to grow correctly, but the markers don't grow:
https://youtu.be/LsaAzwsvyVI

(MacOS, MS Office 2011)

I suspect the answer lies in the PPT XML code.

**Comment by saulhidalgoaular** [comment] 2018-11-06 09:37
Somehow I cannot reproduce it anymore.... It was happening all the time, but now it works... I am going to retake it later.

**Comment by helenayele** [comment] 2018-11-07 15:08
I can't reproduce it as well. 
[DebriefExport-95_12_12_11_01.PPTX](https://github.com/debrief/debrief/files/2557904/DebriefExport-95_12_12_11_01.PPTX)

**Comment by IanMayo** [comment] 2018-11-07 15:17
Ok. It's an important issue, I'm reluctant to close it immediately.  @helenayele - could you make yourself a calendar appointment to come back & re-test this next Wednesday.

The `develop` branch will be in a different state by then - maybe you can re-trigger it.

**Comment by helenayele** [comment] 2018-11-14 11:16
Working as expected , here is the PPT I have got in today's test - 
[DebriefExport-95_12_12_11_19.PPTX](https://github.com/debrief/debrief/files/2580463/DebriefExport-95_12_12_11_19.PPTX)

**Comment by helenayele** [comment] 2019-01-24 08:48
The issue is no more reproducible so closing it..

**Closed by helenayele** 2019-01-24 08:48 UTC
