### ISSUE TITLE
Possible zoom problem with new XY Charts

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1218] opened 2015-05-06 09:58 UTC
I've got a problem with the new XY charts.  

* open **sample.dpf**
* right-click on **Track:Collingwood** and select *XY Plot**
* select **Course** as the attribute to view
* when it opens, make the xy plot about 650 pixels wide (chart 1 below)
* zoom in on the "peak" in the course at around 09:30
* the zoomed in area is shown
* do a reverse drag (upwards & to the left) to rescale the axes
* make the chart 50% wider (about 900 pixels)  (chart 2 below)
* repeat the zoom on the peak 
* an empty area is shown. The time period is actually to the left of the desired area  (chart 3 below).

I can't reproduce this issue with the JFreeChart originals.  It looks like an SWT resize event isn't being propagated to the underlying chart - so the chart things a different area has been zoomed in on.

### Chart 1
![chart1](https://cloud.githubusercontent.com/assets/1108513/7491118/3183aec0-f3de-11e4-80c2-d3c1c6171a22.png)

### Chart 2
![chart2](https://cloud.githubusercontent.com/assets/1108513/7491120/3187480a-f3de-11e4-8d02-e62c93ea6e1d.png)

### Chart 3
![chart3](https://cloud.githubusercontent.com/assets/1108513/7491119/3186a166-f3de-11e4-9439-dd2032f7bd50.png)

**Comment by pecko** [comment] 2015-05-08 18:51
@IanMayo Could you create screencast?

**Comment by IanMayo** [comment] 2015-05-11 11:26
Video made, and uploaded here:
https://www.youtube.com/watch?v=zNinfubFzdA

(though it may take a minute or two more for YouTube to finish processing it)

In the first part of the video you will see me select an area to zoom in on.  The area displayed will always be to the left (before) the selected area.

In the second part of the video you will see that when I click on a data-point, the cross-hairs actually jump to a point further left (before) the one I clicked upon.

**Comment by pecko** [comment] 2015-05-13 00:18
Sorry, I don't understand the issue.

You call "zoom in" three times. They are correct. Right?
Your issue is just click and shown cross-hairs. 
I can reproduce/see the issue with cross-hairs, but can't reproduce some issue with zooming.

In any case, it is a JFreeChart bug and we have to fix it in the JFreeChart code.

**Comment by IanMayo** [comment] 2015-05-13 08:18
Yes, I call "zoom in" 3 times. But, it zooms in on the wrong location each time.  The time period displayed in the zoom doesn't match the area I dragged with the mouse.

I'm pretty sure this is related to the cross-hair clicks issue.  

I think that SWT JFreeChart isn't converting from screen coords (the mouse click) to graph coords (the chart zoom or crosshair display).

**Comment by IanMayo** [comment] 2015-05-13 12:00
Hmm, it may not purely be a SWT JFreeChart bug, since the zoom works correctly in the SWTTimeSeriesDemo sample file.

**Comment by pecko** [comment] 2015-05-13 15:31
I will check difference betwwen swt and swing chart today later.

**Comment by pecko** [comment] 2015-05-14 20:38
SWT chart doesn't work correctly when an off-screen buffer isn't used and a chart is scaled (>800x600).
It is probably a bug in SWT JFreeChart.

I have fixed it by always using an off-screen buffer.

The PR: https://github.com/debrief/debrief/pull/1236

Notice: max scrren size for ChartPanel is 1024X768 (after that JFreeChart uses scale), but for CahrtComposite is 800x600. We can also use 1024X768 without changing the JFreeChart code.

**Comment by pecko** [comment] 2015-05-15 13:08
I suppose that we can close this issue.

**Comment by IanMayo** [comment] 2015-05-15 13:22
No, there is one outstanding issue.  Let me record it:
[CrossHairLocation.mov | uploaded via ZenHub](https://files.zenhub.io/5555f2d1cff2eb104a4bfa24)


The problem is: when we return to view the full plot from a zoomed-in view, the crosshair location text is displayed in the wrong location.

Would you mind looking into this?

**Comment by pecko** [comment] 2015-05-15 13:25
I can't see the file (*mov). Could you reproduce the issue with the SWTTimeSeriesDemo file?

**Comment by IanMayo** [comment] 2015-05-15 13:41
will email file to you.

**Comment by pecko** [comment] 2015-05-15 13:48
Thanks. I will check it.

**Comment by pecko** [comment] 2015-05-17 22:36
I think that the issue with cross hair text happens mostly because the text isn't shown when changed.
For instance, in current code you need click twice to change it. This happens because SWT and AWT handles mouse events differently. I have try to fix by overriding MouseUp event. that is probably a bug in ChartComposite. 
Also, I have try to fix showing the text in progress listener (XYPlotView). I use JFreeChart.setNotify(true) instead of adding/removing annotation.

The PR: https://github.com/debrief/debrief/pull/1238
Now, cross hair location text is correctly shown. When return to full plot, cross hair location text contains the location when you press mouse down (starting reverse zoom). It is the same as in swing version.

**Closed** 2015-05-18 09:46 UTC
Labels: bug
