### ISSUE TITLE
Time player and vertical time bar just pause when changing small steps while playing

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4054] opened 2019-04-18 16:13 UTC
### Steps to reproduce:
1. Load sample.dpf
2. Select Range  and plot xy plot
3. Go to time ribbon and play it
4. See that the vertical time bar just is in sync with the time in controller.
5. Change small step value
6. See that the player in controller and the vertical time bar in the XY Grapth just paused for some seconds.
Video:
[changing_small_Steps_while_playing.zip](https://github.com/debrief/debrief/files/3095247/changing_small_Steps_while_playing.zip)

**Comment by saulhidalgoaular** [comment] 2019-04-20 16:16
Good afternoon @helenayele . I am trying to reproduce it, but it also works normally in my computer.
I think it is due CPU power. I will check the why the XY Plot is using more CPU than before.

**Comment by IanMayo** [comment] 2019-05-07 13:18
Ok, sorted.

**Comment by helenayele** [comment] 2019-05-07 13:57
But I am experiencing the same behavior at my end

**Comment by IanMayo** [comment] 2019-05-07 13:59
Ok @helenayele - let's investigate further :-)

**Comment by saulhidalgoaular** [comment] 2019-06-01 17:36
Good afternoon.

I have tested this issue again on the old computer, but it runs smoothly here. I see the video you have attached, but I am not able to reproduce it.

My computer specifications:
Core i5 2410 - 2.3Ghz
4 GB RAM.
Windows 7 Professional 32 Bits.

**Comment by helenayele** [comment] 2019-06-03 05:25
Okay Saul , let me try it again and see if I can reproduce it again

**Comment by helenayele** [comment] 2019-06-03 06:27
Yes, still reproducing here. As you can say it can be machine performance issue, will check it hopefully after a week on new machine with much better performance. And we can hold it till then

**Comment by helenayele** [comment] 2019-07-10 14:37
I tried to test on my latest laptop. 
And while the track was playing if I change the small step value or anything in edit properties window and press apply, the track stop playing at all. I think this seems new requirement than before. @IanMayo  would you confirm please?

**Comment by saulhidalgoaular** [comment] 2019-08-03 14:13
Good afternoon.

I have tested it again, and yes, it now stops the play when any property is changed and applied. I consider it a very reasonable. What do you think @IanMayo ?

**Comment by helenayele** [comment] 2019-09-03 13:07
@IanMayo  Can we take this as valid requirement and close the issue?

**Comment by saulhidalgoaular** [comment] 2019-11-13 04:45
I consider it works well now. I would suggest to close this issue.

**Closed** 2019-11-13 09:00 UTC
Labels: D-Lite, bug

**Comment by helenayele** [comment] 2019-11-13 14:09
Thanks both - Verified.
