### ISSUE TITLE
Sometimes dragging features in full debrief don't work

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4586] opened 2019-10-21 10:56 UTC
After launching full debrief, when I try to use drag track segment or drag component, or drag whole feature buttons , they don't work and logs this exception
java.lang.NullPointerException
	at org.mwc.debrief.core.actions.DragFeature$DragFeatureMode.doMouseUp(DragFeature.java:427)
	at org.mwc.cmap.plotViewer.editors.chart.SWTChart.doMouseUp(SWTChart.java:928)
	at org.mwc.cmap.plotViewer.editors.chart.SWTChart$3.mouseUp(SWTChart.java:647)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:224)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1056)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)

### Steps to reporoduce:
1. Launch full debrief
2. Open midflower2.dpf file
3. select drag track segment and try to drag it.
[![Image from Gyazo](https://i.gyazo.com/486078a635ebb1259a9ca8843cb71865.gif)](https://gyazo.com/486078a635ebb1259a9ca8843cb71865)

**Comment by IanMayo** [comment] 2019-10-21 16:15
@helenayele - I can't reproduce it yet. Could you try and identify some steps that repeatably throw the exception?

**Comment by helenayele** [comment] 2019-10-22 07:06
hmm, today I tried to launch Full debrief many times and tried to drag , but I can always drag without any failures. So can't reproduce it. But Yesterday I was able to get this issue 1 times at least in 3 launch of debrief.

**Comment by IanMayo** [comment] 2019-10-22 07:38
Sadly it looks like there's some weird situation where it's failing. 

Let's close this issue, so there are fewer "moving parts".  But, as soon as we find something reproducible we'll either re-open this issue, or create a new one to cover it.

**Closed by IanMayo** 2019-10-22 07:38 UTC
Labels: bug
