### ISSUE TITLE
Don't allow to edit source of Narrative entry from property window

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3765] opened 2019-02-15 08:45 UTC
Currently after loading Narratives in D-Lite, a user can edit Source of narrative entry from property dialog. The user can enter non-existent track name while editing and yet D-Lite accepts the values.

[![Image from Gyazo](https://i.gyazo.com/b69759b8f6186a5192f4ed90fad77041.png)](https://gyazo.com/b69759b8f6186a5192f4ed90fad77041)

### Expected Result:
Don't allow to edit the source field of narrative entry at all.

**Comment by IanMayo** [comment] 2019-05-02 12:52
Sorry I'm getting to this so late, ladies.  It is intended behaviour that a non-present track can be assigned as the Source.

In some instances the Source is the name of the person who is maintaining a diary of what's happening.

Or, it may be a log-file captured by some system on board the ship.

So, I'm going to close this issue.  I'm also going to have to (reluctantly) close the PR.

**Closed by IanMayo** 2019-05-02 12:52 UTC
Labels: D-Lite, bug

**Comment by helenayele** [comment] 2019-05-02 13:40
Invalid issue
